version: '3'

services:
    postgres:
        image: 'bitnami/postgresql:latest'
        ports:
            - 5432:5432
        restart: always
        environment:
            POSTGRESQL_PASSWORD: "Shanoj123"
        networks:
            - app-tier
        volumes:
            - ./volume:/bitnami/postgresql
    pgadmin4:
        image: 'dpage/pgadmin4:latest'
        restart: always
        ports:
            - 8080:80
        depends_on:
            - postgres
        environment:
            PGADMIN_DEFAULT_EMAIL: "awscerti.shanoj@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "Shanoj123"
        networks:
            - app-tier
    
networks:
    app-tier:
        driver: bridge

